/**
 * AutoGenerated Code By UIPrefabCodeGenerate ==> CodeGenerate
 */

using System;
using System.Collections.Generic;

namespace GameGraphics
{
	public class UIViewConfig
	{
		public static Dictionary<string, Type> NameToTypeDict = new Dictionary<string, Type>()
		{
			{"UIViewStartGame", typeof(UIViewStartGame)},
		};
	}
}
