/**
 * AutoGenerated Code By UIPrefabCodeGenerate ==> CodeGenerate
 */

using UnityEngine.UI;

namespace GameGraphics
{
	public class UIViewStartGameBase : UIViewBase
	{
		protected Button _buttonSingleMode;
		protected virtual void OnButtonSingleModeClick(){ }
		protected Button _buttonTeamMode;
		protected virtual void OnButtonTeamModeClick(){ }
		protected override void BindWidgets()
		{
			_buttonSingleMode = _root.transform.Find("<Button>SingleMode").GetComponent<Button>();
			_buttonSingleMode.onClick.AddListener(OnButtonSingleModeClick);
			_buttonTeamMode = _root.transform.Find("<Button>TeamMode").GetComponent<Button>();
			_buttonTeamMode.onClick.AddListener(OnButtonTeamModeClick);
		}
		protected override string GetPrefabPath()
		{
			return "Prefabs/UIGraphics/UIViews/UIViewStartGame.prefab";
		}
	}
}
