/**
 * UIPrefab转代码
 */

using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace Editor.UIPrefabCodeGenerate
{
    public class UICodeGenerate
    {
        /// <summary>
        /// 代码导出路径
        /// </summary>
        public static string CodeGenerateExportPath = "Scripts/GameGraphics/UIViews/AutoGenerated";
        
        [MenuItem("Assets/UIPrefabCodeGenerate/CodeGenerate")]
        public static void Generate()
        {
            var sb = new StringBuilder();
            sb.Append(LineText("/**"));
            sb.Append(LineText(" * AutoGenerated Code By UIPrefabCodeGenerate ==> CodeGenerate"));
            sb.Append(LineText(" */\n"));
            sb.Append(LineText("using UnityEngine.UI;\n"));
            var prefab = Selection.activeObject as GameObject;
            sb.Append(LineText($"public class {prefab.name}Base : UIViewBase"));
            sb.Append(LineText("{"));
            var childs = prefab.transform.GetComponentsInChildren<Transform>(true);
            for (int i = 0; i < childs.Length; i++)
            {
                var componentLineText = GetComponentLineText(childs[i]);
                if (!string.IsNullOrEmpty(componentLineText))
                {
                    sb.Append(componentLineText);
                }
            }
            sb.Append(LineText("}"));
            var dirPath = Path.Combine(Application.dataPath, CodeGenerateExportPath);
            if (!Directory.Exists(dirPath)) Directory.CreateDirectory(dirPath);
            File.WriteAllText(Path.Combine(dirPath, $"{prefab.name}Base.cs"), sb.ToString());
            AssetDatabase.Refresh();
        }

        public static string GetComponentLineText(Transform transform)
        {
            var name = transform.name;
            if (name.StartsWith("<") && name.Contains(">"))
            {
                var index = name.IndexOf(">");
                var componentType = name.Substring(1, index - 1);
                var componentName = $"_{componentType.ToLower()}{name.Substring(index + 1)}";
                return LineText($"protected {componentType} {componentName};", 2);
            }
            return "";
        }

        public static string LineText(string text, int tabCount = 0)
        {
            string result = "";
            for (int i = 1; i <= tabCount; i++)
            {
                result = "\t" + result;
            }
            return result + text + "\n";
        }
    }
}